language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x

go_import_path: github.com/sourcegraph/go-langserver

branches:
  only:
    - master

install:
  - go get -d -t ./...
  - go get golang.org/x/lint/golint
  - go test -i ./...

script:
  - cd $TRAVIS_BUILD_DIR
  - go test -timeout 5m -race ./...
